- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Remove all conflicting packages
  apt:
    name:
      - docker.io
      - docker-doc
      - docker-compose
      - docker-compose-v2
      - podman-docker
      - containerd
      - runc
    state: absent
  ignore_errors: true

- name: Install prerequisites for Docker repo
  ansible.builtin.apt:
    name:
    - ca-certificates
    - curl
    state: present

- name: Create /etc/apt/keyrings directory with proper permissions
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker GPG key to /etc/apt/keyrings/docker.asc
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Add Docker APT repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu focal stable"
    filename: docker
    state: present


- name: Update apt cache after adding Docker repo
  ansible.builtin.apt:
    update_cache: yes


- name: Install Docker packages
  ansible.builtin.apt:
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    state: present

- name: Ensure Docker service is running and enabled
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes

- name: Add ubuntu user to docker group
  ansible.builtin.user:
    name: ubuntu
    groups: docker
    append: yes